### ISSUE TITLE
commits

### ISSUE THREAD

**Issue by jyu78749** [Wong12/Algebra-2-Kealing-Light-Matrix-Project#1]
I looked,

Public people aren't allowed to commit. since Ashton is the admin/owner of the repo...it will have to go through him.

**Comment by jyu78749** [comment]
The 2 extra people were from the codenvy demo that was uploaded.

**Comment by ashton-wong** [comment]
Jeriah, I have slack set up and integrated to github, I just need your email to invite you.

**Comment by jyu78749** [comment]
jeriahyu@gmail.com

**Comment by ashton-wong** [comment]
i sent you an invitation
