### ISSUE TITLE
Wikipedia Numbers

### ISSUE THREAD

**Issue by bobpaw** [Wong12/Algebra-2-Kealing-Light-Matrix-Project#6]
This is some of the most horrendous and vomit-inducing pieces of C++ code I have ever seen. There is absolutely no consistency in white space and code like this shouldn't be included in a repository.

**Comment by jyu78749** [comment]
Thanks aiden. It's what happens when someone who doesn't quite yet know proper coding mechanics (Alan) is let loose into the world of embedded c++ without any supervision whatsoever due to everyone else focusing on the raspberry pi. Fatal mistake.
